using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace myMath.Tests
{
    public partial class HelpersTest
    {

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
[ExpectedException(typeof(ArgumentException))]
public void ParseDateStringThrowsArgumentException492()
{
    DateTime dt;
    dt = this.ParseDateString((string)null);
}
    }
}
