using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace myMath.Tests
{
    public partial class HelpersTest
    {


[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void DoSomething2998()
{
    bool b;
    b = this.DoSomething2(0, 0);
    PexAssert.AreEqual<bool>(false, b);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void DoSomething2130()
{
    bool b;
    b = this.DoSomething2(0, 1969057606);
    PexAssert.AreEqual<bool>(true, b);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void DoSomething2863()
{
    bool b;
    b = this.DoSomething2(-925165067, 1969057606);
    PexAssert.AreEqual<bool>(false, b);
}
    }
}
