using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace myMath.Tests
{
    public partial class HelpersTest
    {

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void PerformAnOperation210()
{
    int i;
    i = this.PerformAnOperation(3, 0);
    PexAssert.AreEqual<int>(0, i);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void PerformAnOperation408()
{
    int i;
    i = this.PerformAnOperation(0, 0);
    PexAssert.AreEqual<int>(0, i);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void PerformAnOperation71()
{
    int i;
    i = this.PerformAnOperation(4, 0);
    PexAssert.AreEqual<int>(0, i);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void PerformAnOperation482()
{
    int i;
    i = this.PerformAnOperation(1, 0);
    PexAssert.AreEqual<int>(0, i);
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void PerformAnOperation35()
{
    int i;
    i = this.PerformAnOperation(2, 0);
    PexAssert.AreEqual<int>(0, i);
}
    }
}
