using Microsoft.Pex.Framework;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using myMath;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace myMath.Tests
{
    public partial class HelpersTest
    {

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
[PexRaisedException(typeof(ArgumentOutOfRangeException))]
public void DivideThrowsArgumentOutOfRangeException730()
{
    Helpers s0 = new Helpers();
    Assert.ThrowsException<ArgumentOutOfRangeException>(() => s0.Divide(0,0));
}

[TestMethod]
[PexGeneratedBy(typeof(HelpersTest))]
public void Divide728()
{
    double d;
    Helpers s0 = new Helpers();
    d = this.Divide(s0, 0, 2);
    PexAssert.AreEqual<double>(0, d);
    PexAssert.IsNotNull((object)s0);
}
    }
}
